#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MTGLifeCounter.Resource", IsApplication=true)]

namespace MTGLifeCounter
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int grey_font = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int light_font = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int red_font = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int text_shadow = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int text_shadow_white = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Dice1Dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Dice1Light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Dice2Dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Dice2Light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Dice3Dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Dice3Light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Dice4Dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Dice4Light = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Dice5Dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Dice5Light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Dice6Dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Dice6Light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int forestBg = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int MinusButtonDark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int MinusButtonLight = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int mountainBg = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int mtg = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int plainsBg = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int PlusButtonDark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int PlusButtonLight = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int swampBg = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int waterBg = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int mv_LayoutRoot = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int mv_OpponentDecreaseHealth = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int mv_OpponentDiceValue = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int mv_OpponentDiceView = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int mv_OpponentHealth = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int mv_OpponentIncreaseHealth = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int mv_OpponentLayout = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int mv_OpponentMainView = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int mv_OpponentWinsDiceRoll = 2131099655;
			
			// aapt resource value: 0x7f06000c
			public const int mv_PlayerDecreaseHealth = 2131099660;
			
			// aapt resource value: 0x7f060010
			public const int mv_PlayerDiceValue = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int mv_PlayerDiceView = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int mv_PlayerHealth = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int mv_PlayerIncreaseHealth = 2131099661;
			
			// aapt resource value: 0x7f060009
			public const int mv_PlayerLayout = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int mv_PlayerMainView = 2131099658;
			
			// aapt resource value: 0x7f06000f
			public const int mv_PlayerWinsDiceRoll = 2131099663;
			
			// aapt resource value: 0x7f060014
			public const int mv_menu = 2131099668;
			
			// aapt resource value: 0x7f060011
			public const int mv_menuClose = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int mv_menuToggle = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int mv_menuToggleImg = 2131099667;
			
			// aapt resource value: 0x7f060016
			public const int mv_menu_dice = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int mv_menu_life = 2131099671;
			
			// aapt resource value: 0x7f060015
			public const int mv_menu_reset = 2131099669;
			
			// aapt resource value: 0x7f060018
			public const int mv_menu_settings = 2131099672;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
